{
 "title": "Recruitment Dashboard",
 "time": { "from": "2024-04-06T15:00:31.431Z", "to": "2024-06-05T15:00:31.431Z" },
 "panels": [
  {
   "title": "Average filling Time (in days)",
   "type": "stat",
   "description": "Average number of days it takes to fill a vacancy",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg_time_to_fill\nFROM recruitment_stats\nORDER BY stats_date DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Average Hiring Time (in days)",
   "type": "stat",
   "description": "Calculated the avg time to go from the start of the hiring process to the hired status. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg_time_to_hire\nFROM recruitment_stats\nORDER BY stats_date DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Vacancies per status",
   "type": "bargauge",
   "description": "Number of vacancies in each stage updated as per the last entry in the database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH VAC_OPEN AS (\r\n Select count(*) as nr_vac_open\r\n from jira_issues \r\n WHERE issue_type = 'VACANCY'\r\n AND current_status = 'VAC_OPEN'\r\n),\r\nKDD_IN_PROCEDURE AS (\r\n Select count(*) as nr_kdd_in_procedure\r\n from jira_issues \r\n WHERE issue_type = 'VACANCY'\r\n AND current_status = 'KDD_IN_PROCEDURE'\r\n),\r\n GEEN_KDD_IN_PROCEDURE AS (\r\n Select count(*) as nr_geen_kdd_in_procedure\r\n from jira_issues \r\n WHERE issue_type = 'VACANCY'\r\n AND current_status = 'GEEN_KDD_IN_PROCEDURE'\r\n),\r\nCLOSED___NIET_VERVULD AS (\r\n Select count(*) as closed_niet_vervuld\r\n from jira_issues \r\n WHERE issue_type = 'VACANCY'\r\n AND current_status = 'CLOSED___NIET_VERVULD'\r\n ),\r\n CLOSED___VERVULD AS (\r\n Select count(*) as closed_vervuld\r\n from jira_issues \r\n WHERE issue_type = 'VACANCY'\r\n AND current_status = 'CLOSED___VERVULD')\r\nSELECT\r\nnr_vac_open,\r\nnr_kdd_in_procedure,\r\nnr_geen_kdd_in_procedure,\r\nclosed_niet_vervuld,\r\nclosed_vervuld\r\nFROM\r\nCLOSED___VERVULD,\r\nCLOSED___NIET_VERVULD,\r\nGEEN_KDD_IN_PROCEDURE,\r\nKDD_IN_PROCEDURE,\r\n VAC_OPEN;"
    }
   ]
  },
  {
   "title": "Applicants per stage",
   "type": "bargauge",
   "description": "number of applicants for each stage updated as per the last entry in the database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT open, beoordeling, eerste_gesprek, tweede_gesprek,derde_gesprek\nFROM applicants_stage_log\nWHERE log_date = (\n    SELECT MAX(log_date)\n    FROM applicants_stage_log\n);\n"
    }
   ]
  },
  {
   "title": "Filled Vacancies",
   "type": "gauge",
   "description": "Percentage of how many of the vacancies have been filled",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH total_issues AS (\n    SELECT\n        COUNT(*) AS total\n    FROM\n        jira_issues \n    WHERE\n        issue_type = 'VACANCY'\n),\nfilled_issues AS (\n    SELECT\n        COUNT(*) AS filled\n    FROM\n        jira_issues \n    WHERE\n        current_status = 'CLOSED___VERVULD'\n        AND \n        issue_type = 'VACANCY'\n)\n\nSELECT\n    'Filled Issues' AS label,\n    round(filled::NUMERIC / total * 100) AS percentage\nFROM\n    filled_issues, total_issues;\n"
    }
   ]
  },
  {
   "title": "Applicants reaching stage",
   "type": "gauge",
   "description": "Percentage of how many applicants reach each stage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH total_applicants AS (\n  SELECT\n    COUNT(*) AS total\n  FROM\n    jira_issues\n  WHERE\n    issue_type = 'APPLICANT'\n),\nreached_beoordeling AS (\n  SELECT\n    COUNT(*) AS applicants_in_beoordeling\n  FROM\n    jira_issues\n  WHERE\n    issue_type = 'APPLICANT'\n    AND NOT (current_status = 'OPEN')\n),\nreached_eerste_gesprek AS (\n  SELECT\n    COUNT(*) AS applicants_in_eerste\n  FROM\n    jira_issues\n  WHERE\n    issue_type = 'APPLICANT'\n    AND NOT current_status = 'OPEN'\n    AND NOT current_status = 'BEOORDELING'\n    AND NOT current_status = 'CLOSED___NIET_OP_GESPREK'\n),\nreached_tweede_gesprek AS (\n  SELECT\n    COUNT(*) AS applicants_in_tweede\n  FROM\n    jira_issues\n  WHERE\n    issue_type = 'APPLICANT'\n    AND NOT current_status = 'OPEN'\n    AND NOT current_status = 'BEOORDELING'\n    AND NOT current_status = 'CLOSED___NIET_OP_GESPREK'\n    AND NOT current_status = 'EERSTE_GESPREK'\n    AND NOT current_status = 'CLOSED___NA_EERSTE_GESPREK'\n),\nreached_derde_gesprek AS (\n  SELECT\n    COUNT(*) AS applicants_in_derde\n  FROM\n    jira_issues\n  WHERE\n    issue_type = 'APPLICANT'\n    AND NOT current_status = 'OPEN'\n    AND NOT current_status = 'BEOORDELING'\n    AND NOT current_status = 'CLOSED___NIET_OP_GESPREK'\n    AND NOT current_status = 'EERSTE_GESPREK'\n    AND NOT current_status = 'CLOSED___NA_EERSTE_GESPREK'\n    AND NOT current_status = 'TWEEDE_GESPREK'\n    AND NOT current_status = 'CLOSED___NA_TWEEDE_GESPREK'\n)\nSELECT\n  (applicants_in_beoordeling :: NUMERIC / total * 100) AS percentage_op_beoordeling,\n  (applicants_in_eerste :: NUMERIC / total * 100) AS percentage_op_eerste_gesprek, \n  (applicants_in_tweede :: NUMERIC / total * 100) AS percentage_op_tweede_gesprek,\n  (applicants_in_derde :: NUMERIC / total * 100) AS percentage_op_derde_gesprek\n\nFROM\n  total_applicants,\n  reached_beoordeling,\n  reached_eerste_gesprek,\n  reached_tweede_gesprek,\n  reached_derde_gesprek;"
    }
   ]
  },
  {
   "title": "Number of applications (by month)",
   "type": "barchart",
   "description": "Number of applications of both Jira and LinkedIn in each month, for past 12 months",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(DATE_TRUNC('month', application_date), 'Month YYYY') AS month_label,\r\n    COUNT(*) AS applicants_number\r\nFROM (\r\n    SELECT application_date FROM application_events \r\n    UNION ALL\r\n    SELECT application_date FROM linked_in_applicant\r\n) AS combined_data\r\nGROUP BY\r\n    month_label\r\nORDER BY\r\n    MIN(application_date) DESC\r\nLIMIT 12;\r\n"
    }
   ]
  },
  {
   "title": "Number of hires (by month)",
   "type": "barchart",
   "description": "Number of hires in each month, for past 12 months",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_CHAR(DATE_TRUNC('month', hire_date), 'Month YYYY') AS month_label,\n    COUNT(*) AS hires\nFROM\n    hiring_events \nGROUP BY\n    month_label\nORDER BY\n    MIN(hire_date) desc\nLIMIT 12;"
    }
   ]
  },
  {
   "title": "How did people find us?",
   "type": "piechart",
   "description": "Most recent data from the google form questionnaire",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  other,\r\n  via_internship,\r\n  via_job_board,\r\n  via_network,\r\n  via_recruitment_agency,\r\n  via_school_activity,\r\n  via_search_engine,\r\n  via_social_media\r\nFROM\r\n  forms_stats\r\nWHERE \"timestamp\"= (\r\n    SELECT MAX(\"timestamp\")\r\n    FROM forms_stats\r\n);\r\n"
    }
   ]
  },
  {
   "title": "Applicants per stage (over time)",
   "type": "timeseries",
   "description": "Number of applicants in each stage as function of time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  open,\r\n  beoordeling,\r\n  eerste_gesprek,\r\n  tweede_gesprek,\r\n  derde_gesprek,\r\n  log_date\r\nFROM\r\n  applicants_stage_log\r\nORDER BY\r\n  log_date"
    }
   ]
  },
  {
   "title": "Applications per day",
   "type": "timeseries",
   "description": "Number of applicants each day",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n    application_date AS date,\n    COUNT(*) AS num_applicants\nFROM\n    application_events\nGROUP BY\n    application_date\nORDER BY\n    application_date;"
    }
   ]
  },
  {
   "title": "Hires per day",
   "type": "timeseries",
   "description": "Number of hired applicants each day",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n    hire_date AS date,\n    COUNT(*) AS num_applicants\nFROM\n    hiring_events\nGROUP BY\n    hire_date\nORDER BY\n    hire_date;"
    }
   ]
  },
  {
   "title": "Number of Intern Applications (by month)",
   "type": "barchart",
   "description": "Number of applications by interns in each month, over last 12 months",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(DATE_TRUNC('month', application_date), 'Month YYYY') AS month_label,\r\n    COUNT(*) AS applicants_number\r\nFROM \r\n    intern_application_events \r\nGROUP BY\r\n    month_label\r\nORDER BY\r\n    MIN(application_date) DESC\r\nLIMIT 12;\r\n"
    }
   ]
  },
  {
   "title": "Number of Interns hired (by month)",
   "type": "barchart",
   "description": "Number of interns that where hired in each month, for past 12 months",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(DATE_TRUNC('month', hire_date), 'Month YYYY') AS month_label,\r\n    COUNT(*) AS hire_number\r\nFROM \r\n    intern_hiring_events \r\nGROUP BY\r\n    month_label\r\nORDER BY\r\n    MIN(hire_date) DESC\r\nLIMIT 12;\r\n"
    }
   ]
  }
 ]
}